### PR TITLE
Compiles javascript source file directly into code. Removes Bundle-loading.

### PR DESCRIPTION
**Pull request by mbishop-fiksu**
Removes the requirement of specifying a bundle. The compiler now makes a string constant from the javascript source and always uses that when seeding the WebView.

### CODE REVIEW

**Comment by mbishop-fiksu** [comment]
Going to try and make it more explicit what is public.

**Comment by mbishop-fiksu** [comment]
Okay, we're back on.

**Comment by lokimeyburg** [comment]
@mbishop-fiksu That's a cool way of including the JS. Do you mind explaining the benefit this would provide? Is it just performance? (PS: there's been a few changes to master that you might want to merge in).

**Comment by mbishop-fiksu** [comment]
@lokimeyburg Be happy to answer your very good question.

It's more than performance. Let's say a developer wants to write a plugin that contains WebViewJavascriptBridge. With the current system, the developer needs to ask anyone using the plugin, "can you also please include this resource in your app?". By removing the resource and compiling the code into the plugin, the only dependency needed to include the plugin is the library.

**Comment by lokimeyburg** [comment]
@mbishop-fiksu Cool. Thanks for the explanation. My only worry at the moment with this PR is hiding the Javascript (in an Objective-C file) and obscuring an implantation detail (how it get's added to your project). For a start, I think renaming the file to something like `WebViewJavascriptBridge_JS.m` might make it more clear that "this is where the Javascript lives". Secondly, adding a comment in the file about why we're doing it this way would go a long way for someone figure out why we're not just including a Javascript file.

I'll take a deeper look at the PR later next week when I'm back from vacation. Good job - I didn't know about the preprocessor trick!

**Comment by marcuswestin** [comment]
+1 for separate file, clear mention in the code of what's going on, and merge into master

**Pull request merged**
