### PR TITLE
[mod]use 'decisionHandler(WKNavigationActionPolicyCancel)' to replace…

### PR DESCRIPTION
**Pull request by lbj96347**
Here is my reason.

https://github.com/marcuswestin/WebViewJavascriptBridge/issues/163

### CODE REVIEW

**Comment by marcuswestin** [comment]
@lokimeyburg please review and merge or close.

**Comment by marcuswestin** [comment]
I spent the day doing a bunch of changes - I'll take on this and the other PRs :)

Great explanation in #163 @lbj96347, thanks!

**Comment by marcuswestin** [comment]
@lbj96347 I really appreciate that sort of thoroughness. I'm giving you repo access. Use responsibly please :)

**Comment by lbj96347** [comment]
@marcuswestin Don’t mention it. :-) We also thank you for your project.Our app ["留白·WHITE"](http://liubaiapp.com) uses WebViewJavascriptBridge.It could be a quite important part in our app.

**Pull request merged**
