### PR TITLE
Master

### PR DESCRIPTION
**Pull request by vontio**
show js error msg and line number
if use try catch, user will not know what cause error

### CODE REVIEW

**Comment by marcuswestin** [comment]
Thanks! I think it's good but I have a few hesitations. What do you think:

- an alert box is very invasive. I don't think we should cause apps to show one in prod.
- if someone wants to catch all errors in prod using onerror, then the right thing to do is to report the error to your server (not show an alert box with user-incomprehensible debug info)
- if someone has set window.onerror, then I agree that we should probably propagate the error inside the 'catch' block, since we're otherwise silently eating up errors
- since console.log shows up inside Xcode for debug builds, we should still be doing that. 

If you agree, then I propose a PR which simply adds an 'if (window.onerror) { throw err }' inside the catch block. Also, please mind the white space+indentation.

What do you think?

Cheers, and thanks again!

**Comment by vontio** [comment]
Hi there are some drawbacks if use try catch throw

- user script may throw at load time,if no onerror is set,js will hang there
- rethrow an exception will hidden the real error line number

I think a default onerror hook is a better choice.

use alert instead console.log because console.log will output nothing to my xcode console.
I agree not show error alert to user,I will change alert to console.log

**Comment by marcuswestin** [comment]
- If throwing at load time, the suggested onerror won't work either (since
wvjb js code won't have run yet), no?
- does re-throw of the caught error not maintain the line number inside
'err.stack'?

**Comment by vontio** [comment]
hi

- I tested again. at load time can't  catch too.
- can catch error in setupWebViewJavascriptBridge
- if inject before load user script may catch the error at load time.
- if user add a onerror hook the line number remains '1'.
- in my test, the onerror hook in ios can't get the err obj.


Marcus Westin <notifications@github.com>于2016年3月25日周五 上午9:28写道：

> - If throwing at load time, the suggested onerror won't work either (since
> wvjb js code won't have run yet), no?
> - does re-throw of the caught error not maintain the line number inside
> 'err.stack'?
>

**Pull request merged**
