### PR TITLE
fix ios11, update test enviroment

### LINKED ISSUE #302: I get crash in iOS11 .....
'Completion handler passed to -[WKWebViewJavascriptBridge webView:decidePolicyForNavigationAction:decisionHandler:] was not called'

reason: 'Completion handler passed to -[WKWebViewJavascriptBridge webView:decidePolicyForNavigationAction:decisionHandler:] was called more than once'

How to  resolve  this  problem ??  thank you .

# WVJB Bug Report

Thanks for reporting an issue with WebViewJavascriptBridge.

### Do these 4 things and I will fix your problem!

1. Go to https://github.com/marcuswestin/WebViewJavascriptBridge and click Fork.
2. Clone your fork, `cd` into it and run `make test`. All tests should pass!
3. Edit `Tests/WebViewJavascriptBridgeTests/BridgeTests.m` and create a new, failing test which demostrates your issue.
4. Create a pull request for https://github.com/marcuswestin/WebViewJavascriptBridge

#### That's it!

I will take it from there and promise that I'll fix your problem ASAP.

#### If you don't do this then I can't help you!

And I probably won't :)

Cheers,
@marcuswestin

### LINKED ISSUE #315: crash at ios11
use WKWebview in iOS11, will crash at webView:decidePolicyForNavigationAction:decisionHandler method.
the crash reason:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Completion handler passed to -[WKWebViewJavascriptBridge webView:decidePolicyForNavigationAction:decisionHandler:] was called more than once'

### PR DESCRIPTION
**Pull request by ronhippler**
fix #315 
fix #302

### CODE REVIEW

**Comment by marcuswestin** [comment]
Thank you. I will be looking at this no later than end of next week, but
you as soon as this weekend.

Thanks for the patience (and code!) 👍🙏

**Comment by hpoul** [comment]
seems to fix ios 11 crashes for me :-) any news on a merge @marcuswestin ? :-D
thanks!

**Comment by marcuswestin** [comment]
Bug fixed in #296. Reviewing additional changes.

**Comment by marcuswestin** [comment]
The remaining changes have effectively been merged in through other commits.

Thank you very much @ronhippler!

**Comment by BhavinBhadani** [comment]
@ronhippler can u help me please?

What If I am calling button using JS onClick event? How to handle that? Can u guide me? How to call that playSound button?

`<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title>XYZ</title>

    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css">

    
    <link href="css/bootstrap.min.css" rel="stylesheet">

    
    <link href="css/mdb.min.css" rel="stylesheet">

    
    <style rel="stylesheet">
        /* TEMPLATE STYLES */

        main {
            margin-top: 3rem;
        }

        main .card {
            margin-bottom: 2rem;
        }

        @media only screen and (max-width: 768px) {
            .read-more {
                text-align: center;
            }
        }
    </style>

</head>

<body>

    <main>
        
        <div class="container">

            
            <div class="row">

                <div class="col-md-16">
                    <div class="card">
                        <div class="card-block">
                            <h4 class="card-title">Play Music</h4>
                            <div class="read-more">
                                <a id="sound" class="btn btn-primary" onClick="playSound()">Play</a>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

            </div>
            
            <hr>

        </div>
        
    </main>

    

    
    <script type="text/javascript" src="js/jquery-2.2.3.min.js"></script>

    
    <script type="text/javascript" src="js/tether.min.js"></script>

    
    <script type="text/javascript" src="js/bootstrap.min.js"></script>

    
    <script type="text/javascript" src="js/mdb.min.js"></script>

    <script type="text/javascript" src="js/script.js"></script>

    <script type="text/javascript">

        function playSound() {
            bridge.callHandler('play_sound', {"name": "www/1.mp3"}, function(response) {
            log('JS got response', response, 'js')
            })

        }

    </script>

    <script type="text/javascript">
        function setupWKWebViewJavascriptBridge(callback) {
            if (window.WKWebViewJavascriptBridge) { return callback(WKWebViewJavascriptBridge); }
            if (window.WKWVJBCallbacks) { return window.WKWVJBCallbacks.push(callback); }
            window.WKWVJBCallbacks = [callback];
            window.webkit.messageHandlers.iOS_Native_InjectJavascript.postMessage(null)
        }
    
    setupWKWebViewJavascriptBridge(function(bridge) {

                                   
                                   })
    </script>

</body>

</html>`

**Pull request closed without merging**
