### PR TITLE
WKWebView Support

### PR DESCRIPTION
**Pull request by lokimeyburg**
I've added support for [WKWebView](http://nshipster.com/wkwebkit/) which was requested in issue #84.

**How does it work:**
WKWebView support is opt-in. In order to use WKWebView you need to instantiate the `WKWebViewJavascriptBridge`. The rest of the `WKWebViewJavascriptBridge` API is the same as `WebViewJavascriptBridge`.

1) Import the header file:

```
#import "WKWebViewJavascriptBridge.h"
```

2) Instantiate WKWebViewJavascriptBridge and with a WKWebView object

	WKWebViewJavascriptBridge* bridge = [WKWebViewJavascriptBridge bridgeForWebView:webView handler:^(id data, WVJBResponseCallback responseCallback) {
		// etc
	}];
  

**Where to start**
Take a look at the `WKWebViewJavascriptBridge.m` file first as it has most of the logic. The two important differences are that the delegates for WKWebView have been changed and that the response for evaluating Javascript is now returned in a callback.

| UIWebView | WKWebView Equivalent |
--- | --- | ---
| didFailLoadWithError | didFailNavigation |
| webViewDidFinishLoad | didFinishNavigation |
| webViewDidStartLoad  | didStartProvisionalNavigation |
| shouldStartLoadWithRequest  | decidePolicyForNavigationAction |

**How to test this**
Pull down the branch and try to run the example application. Try running it in XCode 5 and 6 to test out iOS7 and iOS8 respectively. If you're using Pods, point to this branch and see if it works in one of your existing apps.

**Extra**

1. Can someone please test this out on OSX 10.10? I don't have a machine currently running Yosemite. 
2. I'm also currently testing this against a bigger iOS project, [Stacker](http://www.lokimeyburg.com/Stacker/), in the [`feature/wkwebkit`](https://github.com/lokimeyburg/Stacker/tree/feature/wkwebview/Example) branch to make sure WebViewJavascriptBridge works as advertised.
3. I think there's lots of room to DRY up the code between `WebViewJavascriptBridge` and `WKWebViewJavascriptBridge` however I think that should be left for another PR.

### CODE REVIEW

**Comment by edgarchu** [comment]
@karlbecker Did you ever find out if that warning is valid?
re:
> Cannot coexist with UIWebView on iOS 7 and below

**Comment by karlbecker** [comment]
@edgarchu - I haven't tried submitting an app with both UIWebView and WKWebView, so nope, not sure if Apple would reject, if it wouldn't work, or if it would just be a-ok!

**Comment by alleus** [comment]
Any updates on this? Would love to use WebViewJavascriptBridge with WKWebView, and this merge request seems well worked trough.

**Comment by lokimeyburg** [comment]
@alleus Just wanted to add that we've successfully launched a rather large app with both UIWebview and WKWebview without any issue. @marcuswestin what would it take to merge this PR? Make sure it works on iOS 9?

**Comment by karlbecker** [comment]
> Just wanted to add that we've successfully launched a rather large app with both UIWebview and WKWebview without any issue

:clap: :clap: :clap: 

And no tricky techniques needed to hide that you used both, correct, @lokimeyburg ?

**Comment by lokimeyburg** [comment]
Nope no tricks. It's pretty clear in the source code that we're implementing both.

**Comment by marcuswestin** [comment]
Sorry for the delay guys. Getting a startup off the ground can be pretty all-consuming :)

**Comment by marcuswestin** [comment]
Wanna take some credit for your hard work and add a PR with updates to README that notes support of WKWebView :)

**Comment by marcuswestin** [comment]
@lokimeyburg You're now a contributor - very well deserved!

Feel free to act on behalf of WVBJ with the best interest of the project in mind :) Keep me in the loop on anything significant though please.

Cheers,
Marcus

**Comment by marcuswestin** [comment]
If you're interested in doing more right now, here's an interesting PR to consider: #133

**Comment by marcuswestin** [comment]
Also looking interesting: #129

**Comment by lokimeyburg** [comment]
Thank @marcuswestin! Glad to help! I'll be sure to keep things in order. I'll take a look at those PRs tomorrow.

**Comment by marcuswestin** [comment]
Awesome!

**Comment by karlbecker** [comment]
And great job to everyone on an excellent, exciting PR!

**Pull request merged**
